### ISSUE TITLE
ANNOUNCEMENT: Office 365 data load failure due to Customer Lockbox 

### ISSUE THREAD

**Issue by o365analyticssupport** [OfficeDev/MS-Graph-Data-Connect#58]
Thank you for being an early adopter of Microsoft Graph data connect. If you see the error message below while attempting to run a pipeline it is likely that your organization is configured with the Office 365 Customer Lockbox enabled. Currently, we exclude it as a source for the preview Office 365 Connector.

For now, you may ask the tenant admin to temporarily disable Customer Lockbox or begin development with another organization identity.

The error message you will currently see is shown below:

{ "errorCode": "2200", "message": "ErrorCode=UserErrorOffice365DataLoaderError,'Type=Microsoft.DataTransfer.Common.Shared.HybridDeliveryException,Message=Office365
data loading failed to execute. Failed to extract data from Office 365 for Tenant xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx and dataset BasicDataSet_v0.yyy into AzureX account,Source=Microsoft.DataTransfer.ClientLibrary,'", "failureType":
"UserError", "target": "O365toAzureCopyData" }

We will post an update to this issue once we remove this restriction.

**Comment by tlenig** [comment]
We now support Customer Lockbox tenants through Microsoft Graph data connect, thus this issue should no longer be encountered. Please do reach out to dataconnect@microsoft.com if you continue to see a failure.
